/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coursework;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abhinav
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        bg1 = new javax.swing.ButtonGroup();
        mainpnl = new javax.swing.JPanel();
        companylbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        sidepnl = new javax.swing.JPanel();
        userswitchbtn = new javax.swing.JButton();
        adminswitchbtn = new javax.swing.JButton();
        changelbl = new javax.swing.JLabel();
        SwitchPane = new javax.swing.JTabbedPane();
        adminpnl = new javax.swing.JPanel();
        companyenterlbl = new javax.swing.JLabel();
        companytf1 = new javax.swing.JTextField();
        vehicleenterlbl = new javax.swing.JLabel();
        vehicletf2 = new javax.swing.JTextField();
        categoryenterlbl = new javax.swing.JLabel();
        combocb1 = new javax.swing.JComboBox<>();
        destinationenterlbl = new javax.swing.JLabel();
        destinationtf3 = new javax.swing.JTextField();
        priceenterlbl = new javax.swing.JLabel();
        pricetf4 = new javax.swing.JTextField();
        additembtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        adminentrylbl = new javax.swing.JLabel();
        delbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        onlinerb = new javax.swing.JRadioButton();
        deliveryrb = new javax.swing.JRadioButton();
        userpnl = new javax.swing.JPanel();
        userenterlbl = new javax.swing.JLabel();
        searchpricelbl = new javax.swing.JLabel();
        pricesearchtf = new javax.swing.JTextField();
        categorysearchlbl = new javax.swing.JLabel();
        catcb = new javax.swing.JComboBox<>();
        pricesearchbtn = new javax.swing.JButton();
        categorysearchbtn = new javax.swing.JButton();
        sortlbl = new javax.swing.JLabel();
        sortcb = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainpnl.setBackground(new java.awt.Color(255, 255, 255));

        companylbl.setBackground(new java.awt.Color(0, 0, 0));
        companylbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        companylbl.setForeground(new java.awt.Color(255, 255, 255));
        companylbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        companylbl.setText("Shipping Infomation System");
        companylbl.setOpaque(true);

        Table1.setBackground(new java.awt.Color(153, 153, 153));
        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "company", "vehicle", "category", "Destination", "Price", "Payment method"
            }
        ));
        jScrollPane1.setViewportView(Table1);

        sidepnl.setBackground(new java.awt.Color(51, 0, 0));

        userswitchbtn.setBackground(new java.awt.Color(204, 204, 255));
        userswitchbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userswitchbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhinav\\Desktop\\Emerging CW\\icons8-user-30.png")); // NOI18N
        userswitchbtn.setText("User");
        userswitchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userswitchbtnActionPerformed(evt);
            }
        });

        adminswitchbtn.setBackground(new java.awt.Color(204, 204, 255));
        adminswitchbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        adminswitchbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\abhinav\\Desktop\\Emerging CW\\icons8-admin-settings-male-24.png")); // NOI18N
        adminswitchbtn.setText("Admin");
        adminswitchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminswitchbtnActionPerformed(evt);
            }
        });

        changelbl.setBackground(new java.awt.Color(153, 153, 153));
        changelbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        changelbl.setForeground(new java.awt.Color(204, 255, 204));
        changelbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changelbl.setText("Change user");
        changelbl.setOpaque(true);

        javax.swing.GroupLayout sidepnlLayout = new javax.swing.GroupLayout(sidepnl);
        sidepnl.setLayout(sidepnlLayout);
        sidepnlLayout.setHorizontalGroup(
            sidepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(changelbl, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(userswitchbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(adminswitchbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
        );
        sidepnlLayout.setVerticalGroup(
            sidepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepnlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(changelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(userswitchbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sidepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sidepnlLayout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(adminswitchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(539, Short.MAX_VALUE)))
        );

        adminpnl.setBackground(new java.awt.Color(102, 102, 102));

        companyenterlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        companyenterlbl.setText("Shipping company");

        companytf1.setBackground(new java.awt.Color(204, 204, 204));

        vehicleenterlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vehicleenterlbl.setText("Shipping vehicle");

        vehicletf2.setBackground(new java.awt.Color(204, 204, 204));

        categoryenterlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        categoryenterlbl.setText("Shipping category");

        combocb1.setBackground(new java.awt.Color(204, 204, 204));
        combocb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deluxe", "Premium", "Regular", "Normal", "Standard" }));
        combocb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocb1ActionPerformed(evt);
            }
        });

        destinationenterlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        destinationenterlbl.setText("Shipping destination");

        destinationtf3.setBackground(new java.awt.Color(204, 204, 204));

        priceenterlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        priceenterlbl.setText("Shipping price");

        pricetf4.setBackground(new java.awt.Color(204, 204, 204));

        additembtn.setText("ADD ITEMS");
        additembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additembtnActionPerformed(evt);
            }
        });

        clearbtn.setText("CLEAR");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        adminentrylbl.setBackground(new java.awt.Color(0, 0, 0));
        adminentrylbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminentrylbl.setForeground(new java.awt.Color(255, 255, 255));
        adminentrylbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminentrylbl.setText("Admin Detail entry");
        adminentrylbl.setOpaque(true);

        delbtn.setText("DELETE");
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Payment method");

        onlinerb.setBackground(new java.awt.Color(204, 204, 204));
        bg1.add(onlinerb);
        onlinerb.setText("Online");

        deliveryrb.setBackground(new java.awt.Color(204, 204, 204));
        bg1.add(deliveryrb);
        deliveryrb.setText("On delivery");

        javax.swing.GroupLayout adminpnlLayout = new javax.swing.GroupLayout(adminpnl);
        adminpnl.setLayout(adminpnlLayout);
        adminpnlLayout.setHorizontalGroup(
            adminpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminentrylbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(priceenterlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vehicleenterlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(categoryenterlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(companyenterlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(destinationenterlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(adminpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminpnlLayout.createSequentialGroup()
                        .addGroup(adminpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(companytf1)
                                .addComponent(combocb1, 0, 159, Short.MAX_VALUE)
                                .addComponent(destinationtf3)
                                .addComponent(pricetf4))
                            .addComponent(vehicletf2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(adminpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(additembtn, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(clearbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(adminpnlLayout.createSequentialGroup()
                        .addComponent(onlinerb)
                        .addGap(18, 18, 18)
                        .addComponent(deliveryrb)))
                .addGap(98, 98, 98))
        );
        adminpnlLayout.setVerticalGroup(
            adminpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminpnlLayout.createSequentialGroup()
                .addComponent(adminentrylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(adminpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companytf1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyenterlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(additembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adminpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vehicleenterlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vehicletf2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(adminpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryenterlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combocb1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(adminpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destinationenterlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adminpnlLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(destinationtf3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(adminpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceenterlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pricetf4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(adminpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(onlinerb)
                        .addComponent(deliveryrb)))
                .addContainerGap())
        );

        SwitchPane.addTab("Admin", adminpnl);

        userpnl.setBackground(new java.awt.Color(102, 102, 102));

        userenterlbl.setBackground(new java.awt.Color(0, 0, 0));
        userenterlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userenterlbl.setForeground(new java.awt.Color(255, 255, 255));
        userenterlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userenterlbl.setText("User Search");
        userenterlbl.setOpaque(true);

        searchpricelbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchpricelbl.setText("Search according to price:");

        pricesearchtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricesearchtfActionPerformed(evt);
            }
        });

        categorysearchlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        categorysearchlbl.setText("Search according to category:");

        catcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a category", "Deluxe", "Premium", "Regular", "Standard", "Normal" }));
        catcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catcbActionPerformed(evt);
            }
        });

        pricesearchbtn.setText("Search for price");
        pricesearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricesearchbtnActionPerformed(evt);
            }
        });

        categorysearchbtn.setText("Search for category");
        categorysearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorysearchbtnActionPerformed(evt);
            }
        });

        sortlbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sortlbl.setText("Sort");

        sortcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort By:", "Price Ascending", "Price Descending", " " }));
        sortcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortcbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userpnlLayout = new javax.swing.GroupLayout(userpnl);
        userpnl.setLayout(userpnlLayout);
        userpnlLayout.setHorizontalGroup(
            userpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userenterlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(userpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(userpnlLayout.createSequentialGroup()
                        .addGroup(userpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sortlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categorysearchlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchpricelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(userpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userpnlLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(pricesearchtf, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userpnlLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(userpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(catcb, javax.swing.GroupLayout.Alignment.TRAILING, 0, 128, Short.MAX_VALUE)
                                    .addComponent(sortcb, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(userpnlLayout.createSequentialGroup()
                        .addGroup(userpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pricesearchbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categorysearchbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        userpnlLayout.setVerticalGroup(
            userpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userpnlLayout.createSequentialGroup()
                .addComponent(userenterlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(userpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchpricelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pricesearchtf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(userpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categorysearchlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catcb, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(userpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sortlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sortcb, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(categorysearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(pricesearchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        SwitchPane.addTab("User", userpnl);

        javax.swing.GroupLayout mainpnlLayout = new javax.swing.GroupLayout(mainpnl);
        mainpnl.setLayout(mainpnlLayout);
        mainpnlLayout.setHorizontalGroup(
            mainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpnlLayout.createSequentialGroup()
                .addComponent(sidepnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpnlLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(SwitchPane))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                            .addComponent(companylbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        mainpnlLayout.setVerticalGroup(
            mainpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpnlLayout.createSequentialGroup()
                .addComponent(companylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SwitchPane))
            .addComponent(sidepnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Open");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);
        jMenu1.add(jSeparator2);

        jMenuItem3.setText("Exit");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Help");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Help file");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminswitchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminswitchbtnActionPerformed
        // TODO add your handling code here:
        SwitchPane.setSelectedIndex(0);
    }//GEN-LAST:event_adminswitchbtnActionPerformed

    private void userswitchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userswitchbtnActionPerformed
        // TODO add your handling code here:
        SwitchPane.setSelectedIndex(1);
    }//GEN-LAST:event_userswitchbtnActionPerformed

    private void additembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additembtnActionPerformed
        // TODO add your handling code here:
        
        String tf1 = companytf1.getText();
        String tf2 = vehicletf2.getText();
        String tf3 = destinationtf3.getText();
        String tf4 = pricetf4.getText();
        
        
        if(tf1.isEmpty()|| tf2.isEmpty()||tf3.isEmpty()||tf4.isEmpty()){
            JOptionPane.showMessageDialog(mainpnl,"please enter all the fields");
        }
        else{
            if(onlinerb.isSelected()){
                DefaultTableModel model = (DefaultTableModel) Table1.getModel();
                model.addRow(new Object[]{companytf1.getText(),vehicletf2.getText(),combocb1.getSelectedItem().toString(),destinationtf3.getText(),pricetf4.getText(),"online"});
                JOptionPane.showMessageDialog(mainpnl,"data has been added");
                
            }
            else if(deliveryrb.isSelected()){
                DefaultTableModel model = (DefaultTableModel) Table1.getModel();
                model.addRow(new Object[]{companytf1.getText(),vehicletf2.getText(),combocb1.getSelectedItem().toString(),destinationtf3.getText(),pricetf4.getText(),"on delivery"});
                JOptionPane.showMessageDialog(mainpnl,"data has been added");
            }
        
            
        }
        
    
    }//GEN-LAST:event_additembtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
        companytf1.setText("");
        vehicletf2.setText("");
        destinationtf3.setText("");
        pricetf4.setText("");
    }//GEN-LAST:event_clearbtnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       //importing txt file
        FileReader read = null;
        String pathname = "src\\coursework\\text.txt";
        File file = new File(pathname);
        try {
            read = new FileReader(file);
            BufferedReader br = new BufferedReader(read);
            DefaultTableModel model = (DefaultTableModel)Table1.getModel();
            Object[] line = br.lines().toArray();
            for (int i = 0; i < line.length; i++){
                String [] row = line [i].toString().split(",");
                model.addRow(row);
            }
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void sortcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortcbActionPerformed
        // TODO add your handling code here:
        int cbval = sortcb.getSelectedIndex();
        if (cbval == 0) {
         JOptionPane.showMessageDialog(mainpnl,"please select the values below");
        } else if (cbval == 1) {
            sort(0,4);
        } else if(cbval == 2){
            sort(-1,4);
        }
    }//GEN-LAST:event_sortcbActionPerformed

    private void catcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catcbActionPerformed
        // TODO add your handling code here:
          
        
        
    }//GEN-LAST:event_catcbActionPerformed

    private void categorysearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorysearchbtnActionPerformed
        // TODO add your handling code here:
       if(catcb.getSelectedIndex() !=0)
       {
           ArrayList<Integer> catar = new ArrayList<Integer>();
           String categ = (String) catcb.getSelectedItem();
           for(int i = 0; i < Table1.getRowCount(); i++){
               String cattab = (String) Table1.getValueAt(i,2);
               if(categ.equals(cattab)){
                   catar.add(i);
               }
           }
           String den = "";
           for(int j = 0; j<catar.size();j++)
           {
            den = den+Table1.getValueAt(catar.get(j),0).toString()+"\n";
           }
           JOptionPane.showMessageDialog(mainpnl,"the name of the company are:\n"+den);
       } 
        
    }//GEN-LAST:event_categorysearchbtnActionPerformed

    private void pricesearchtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricesearchtfActionPerformed
        // TODO add your handling code here:
        int Pricetf = Integer.parseInt(pricesearchtf.getText());
    }//GEN-LAST:event_pricesearchtfActionPerformed

    private void combocb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combocb1ActionPerformed

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbl = (DefaultTableModel) Table1.getModel();
        
        if(Table1.getSelectedRowCount()==1){
            tbl.removeRow(Table1.getSelectedRow());
            JOptionPane.showMessageDialog(mainpnl,"the row has been deleted");
            
        }
        else{
            if(Table1.getRowCount()==0){
                JOptionPane.showMessageDialog(mainpnl,"There is no row to delete");
            }
            else{
                JOptionPane.showMessageDialog(mainpnl,"Only one row can be deleted at a time");
            }
        }
    }//GEN-LAST:event_delbtnActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try{
            File file = new File("src\\coursework\\helpfile2.pdf");
            if(file.exists()){
                if(Desktop.isDesktopSupported()){
                    Desktop.getDesktop().open(file);
                }
                else{
                    JOptionPane.showMessageDialog(mainpnl,"file format not supported");
                }
            }
            else{
                JOptionPane.showMessageDialog(mainpnl,"file does not exist");
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void pricesearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricesearchbtnActionPerformed
        // TODO add your handling code here:
         //Creating ArrayList for every category
        ArrayList<Integer> priceval = new ArrayList();
	ArrayList<String> compName = new ArrayList();
        ArrayList<String> VehName = new ArrayList();
        ArrayList<String> CatShip = new ArrayList();
        ArrayList<String> DestName = new ArrayList();
        ArrayList<String> PayMode = new ArrayList();
        
	int rowCount = Table1.getRowCount();
	for (int i = 0; i < rowCount; i++) {
                String Company = (String) Table1.getValueAt(i, 0);
                String Vehicle = (String) Table1.getValueAt(i, 1);
                String Category = (String) Table1.getValueAt(i, 2);
                String Destination = (String) Table1.getValueAt(i, 3);
		String valuepri = (String) Table1.getValueAt(i, 4);
                String PayType = (String) Table1.getValueAt(i, 5);
		if(valuepri != null && Company != null && Vehicle != null && Category != null && Destination != null && PayType != null){
			priceval.add(Integer.parseInt(valuepri));
                        compName.add(Company);
                        VehName.add(Vehicle);
                        CatShip.add(Category);
                        DestName.add(Destination);
                        PayMode.add(PayType);
		}
	}
	
	for (int i = 0; i < priceval.size(); i++) {
		int min = i;
		for (int j = i + 1; j < priceval.size(); j++) {
			if (priceval.get(j) < priceval.get(min)) {
				min = j;
			}
		}
		
                //swapping price values
		int priceTemp = priceval.get(min);
		priceval.set(min, priceval.get(i));
		priceval.set(i, priceTemp);
                
                //swapping vehicle values
                String vehiTemp = VehName.get(min);
                VehName.set(min, VehName.get(i));
                VehName.set(i, vehiTemp);
                
                //swapping category values
                String catTemp = CatShip.get(min);
                CatShip.set(min, CatShip.get(i));
                CatShip.set(i, catTemp);
                
                String comTemp = compName.get(min);
                compName.set(min, compName.get(i));
                compName.set(i, comTemp);
                
                String desTemp = DestName.get(min);
                DestName.set(min, DestName.get(i));
                DestName.set(i, desTemp);
		
                String paymenttemp = PayMode.get(min);
                PayMode.set(min, PayMode.get(i));
                PayMode.set(i, paymenttemp);
	}

	int sch = Integer.parseInt(pricesearchtf.getText());
	int low = 0;
	int high = priceval.size();
	int searchedVal = BinarySearch(priceval, low, high, sch);
	
	if(searchedVal == -1){
		JOptionPane.showMessageDialog(mainpnl,"Sorry, There is not any shipping information with the price "+sch+".");
	}else{
		int schPrice = priceval.get(searchedVal);
                String ShipComp = compName.get(searchedVal);
                String ShipVehi = VehName.get(searchedVal);
                String ShipCat = CatShip.get(searchedVal);
                String ShipDest = DestName.get(searchedVal);
                String Payment = PayMode.get(searchedVal);
		JOptionPane.showMessageDialog(mainpnl,"The information of shipping with the price "+schPrice+" is displayed below:\n"+
                        "Company Name: "+ShipComp+"\n"+"Shipping Vehicle: "+ShipVehi+"\n"+"Shipping category: "+ShipCat+
                        "\n"+"Shipping Destination: "+ShipDest + "\n" + "Payment mode: "+Payment);
	} 
    }                                              
    
    //BinarySearch method
    public int BinarySearch(ArrayList<Integer> a, int low, int high, int sch){
	while(low<high){
            int mid = (low+high)/2;
            if(a.get(mid).equals(sch)){
                    return mid;
            }else if(a.get(mid)<sch){
                    low = mid + 1;
            }else{
                    high = mid;
            }
        
        }  return -1;
    }//GEN-LAST:event_pricesearchbtnActionPerformed

    public void sort(int type, int column) {
       
        int rowCount = Table1.getRowCount();
        Integer[] array = new Integer[rowCount];
        for (int i = 0; i < rowCount; i++) {
            String price = (String) Table1.getValueAt(i, column);
            int pric = Integer.parseInt(price);
            if (price != null) {
                array[i] = pric;
            }
        }
        //looping to get data from table
        for (int i = 0; i < array.length; i++) {
            int min = i;
            for (int j = i + 1; j < array.length; j++) {
                
                if (type == 0) {
                    if (array[j].compareTo(array[min])<0) {
                        min = j;
                    }
                } else {
                    if (array[j].compareTo(array[min])>0) {
                        min = j;
                    }
                }
            }
            
            // swapping array values
            Integer temp = array[min];
            array[min] = array[i];
            array[i] = temp;
            
            // swapping company values
            String CompTemp = (String) Table1.getValueAt(i, 0);
            Table1.setValueAt(Table1.getValueAt(min, 0), i, 0);
            Table1.setValueAt(CompTemp, min, 0);

            // swapping vehicle values
            String VehicleTemp = (String) Table1.getValueAt(i, 1);
            Table1.setValueAt(Table1.getValueAt(min, 1), i, 1);
            Table1.setValueAt(VehicleTemp, min, 1);

            // swapping category values
            String CatTemp = (String) Table1.getValueAt(i, 2);
            Table1.setValueAt(Table1.getValueAt(min, 2), i, 2);
            Table1.setValueAt(CatTemp, min, 2);
            
            // swapping destination values
            String destinationtemp = (String) Table1.getValueAt(i,3);
            Table1.setValueAt(Table1.getValueAt(min,3),i,3);
            Table1.setValueAt(destinationtemp,min,3);
            
            // swapping price values
           String pricetemp = (String) Table1.getValueAt(i,4);
           Table1.setValueAt(Table1.getValueAt(min,4), i, 4);
           Table1.setValueAt(pricetemp,min,4);
            
            String paymenttemp = (String) Table1.getValueAt(i,5);
            Table1.setValueAt(Table1.getValueAt(min,5),i,5);
            Table1.setValueAt(paymenttemp,min,5);

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane SwitchPane;
    private javax.swing.JTable Table1;
    private javax.swing.JButton additembtn;
    private javax.swing.JLabel adminentrylbl;
    private javax.swing.JPanel adminpnl;
    private javax.swing.JButton adminswitchbtn;
    private javax.swing.ButtonGroup bg1;
    private javax.swing.JComboBox<String> catcb;
    private javax.swing.JLabel categoryenterlbl;
    private javax.swing.JButton categorysearchbtn;
    private javax.swing.JLabel categorysearchlbl;
    private javax.swing.JLabel changelbl;
    private javax.swing.JButton clearbtn;
    private javax.swing.JComboBox<String> combocb1;
    private javax.swing.JLabel companyenterlbl;
    private javax.swing.JLabel companylbl;
    private javax.swing.JTextField companytf1;
    private javax.swing.JButton delbtn;
    private javax.swing.JRadioButton deliveryrb;
    private javax.swing.JLabel destinationenterlbl;
    private javax.swing.JTextField destinationtf3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPanel mainpnl;
    private javax.swing.JRadioButton onlinerb;
    private javax.swing.JLabel priceenterlbl;
    private javax.swing.JButton pricesearchbtn;
    private javax.swing.JTextField pricesearchtf;
    private javax.swing.JTextField pricetf4;
    private javax.swing.JLabel searchpricelbl;
    private javax.swing.JPanel sidepnl;
    private javax.swing.JComboBox<String> sortcb;
    private javax.swing.JLabel sortlbl;
    private javax.swing.JLabel userenterlbl;
    private javax.swing.JPanel userpnl;
    private javax.swing.JButton userswitchbtn;
    private javax.swing.JLabel vehicleenterlbl;
    private javax.swing.JTextField vehicletf2;
    // End of variables declaration//GEN-END:variables
}
